const pedidos = [
  {
    id: 101,
    cliente: "Mikael",
    item: "GPU RTX 4090",
    quantidade: 1,
    preco: 12000,
    categoria: "Hardware",
  },
  {
    id: 102,
    cliente: "Ana",
    item: "Teclado",
    quantidade: 5,
    preco: 150,
    categoria: "Periféricos",
  },
  {
    id: 103,
    cliente: "Bruno",
    item: "Bateria Lítio",
    quantidade: 2,
    preco: 800,
    categoria: "Perigosos",
  },
  {
    id: 104,
    cliente: "Carla",
    item: "Monitor 24",
    quantidade: 12,
    preco: 900,
    categoria: "Hardware",
  },
  {
    id: 105,
    cliente: "Diego",
    item: "Mouse Pad",
    quantidade: 2,
    preco: 50,
    categoria: "Periféricos",
  },
  {
    id: 106,
    cliente: "Elena",
    item: "Notebook Pro",
    quantidade: 1,
    preco: 8000,
    categoria: "Hardware",
  },
  {
    id: 107,
    cliente: "Fabio",
    item: "Cadeira Gamer",
    quantidade: 1,
    preco: 1200,
    categoria: "Móveis",
  },
  {
    id: 108,
    cliente: "Gabi",
    item: "Ácido Industrial",
    quantidade: 1,
    preco: 500,
    categoria: "Perigosos",
  },
  {
    id: 109,
    cliente: "Hugo",
    item: "Headset",
    quantidade: 20,
    preco: 200,
    categoria: "Periféricos",
  },
  {
    id: 110,
    cliente: "Iara",
    item: "Webcam 4K",
    quantidade: 3,
    preco: 600,
    categoria: "Periféricos",
  },
];
